language: erlang

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - git clone git://github.com/Olivine-Labs/say.git
  - cd say
  - sudo luarocks make
  - cd ../
  - git clone git://github.com/Olivine-Labs/luassert.git
  - cd luassert
  - sudo luarocks make
  - cd ../
  - git clone git://github.com/Olivine-Labs/busted.git
  - cd busted
  - sudo luarocks make
  - cd ../

script: "busted spec"
